#!/bin/bash

options=(
	style=round
	width=8.0
	hidpi=on
	active_color="gradient(top_left=0xff8839ef,bottom_right=0xffb4befe)"
	inactive_color="gradient(top_right=0xff94e2d5,bottom_left=0xff6c7086)"
	blacklist="Autodesk Fusion 360"
)

borders "${options[@]}"

